module.exports = {
  TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
  TWITTER_BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN,
  TWITTER_AUTH_KEY: process.env.TWITTER_AUTH_KEY,
  TWITTER_AUTH_SECRET: process.env.TWITTER_AUTH_SECRET,
  MAPBOX_TOKEN: process.env.MAPBOX_TOKEN,
};
